= Kafka Event Finder
:toc: macro

Application that allows you to find an event on a topic

toc::[]

== Configuration

=== Default Port

This application runs on port 10000 to ensure it doesn't conflict with other applications that are using default spring boot configuration.
Change the default port in `./config/application.yaml`
----
server:
  port: 10000
----

Swagger UI is available at http://localhost:10000/swagger-ui.html

=== Servers

List of servers to connect to. By default, the application doesn't connect to any servers.
Connections can be made using the connect api and connection strings can be managed using the configuration api.
Configurations can be injected without using config API by managing config in `application.yaml` in the `./config/application.yaml` of the jar file.

===== Server Config Format
----
connections:
  autoConnect: true
  servers:
    - name: preprod
      bootstrapServers: pkc-41wrz.us-east-1.aws.confluent.cloud:9092
      maxBlockMS: 10000
      requestTimeoutMS: 10000
      retryBackoffMS: 10000
      securityProtocol: SASL_SSL
      apiKey: *******
      apiSecret: *******
    - name: onprem
      bootstrapServers: bs1.pd.magkaf.intranet.local:9093,bs2.pd.magkaf.intranet.local:9093,bs3.pd.magkaf.intranet.local:9093,bs4.pd.magkaf.intranet.local:9093
      maxBlockMS: 10000
      requestTimeoutMS: 10000
      retryBackoffMS: 10000
      securityProtocol: SASL_PLAINTEXT
      apiKey: *******
      apiSecret: *******
    - name: perf
      bootstrapServers: pkc-epkd2.us-east-1.aws.confluent.cloud:9092
      maxBlockMS: 10000
      requestTimeoutMS: 10000
      retryBackoffMS: 10000
      securityProtocol: SASL_SSL
      apiKey: *******
      apiSecret: *******
----

==== Start the application
This application requires Java 11, after setting `JAVA_HOME`, the application can be started by running `run.sh`

. CLI
[source,bash]
----
# Build
./gradlew :app:bootJar

# Build and Run
./gradlew :app:bootRun

# Build and run using config provided in config/application.yaml
./run.sh
----

=== Get active connections
=== Connect to a server
=== Disconnect from a server


== Find an event
* By default all searches begin with the lowest offset the topic has. You can use `partition` search strategy and provide
a `%` of the log to skip over.


.Example Search by partition (http://localhost:10000/swagger-ui.html#/topic/searchEventUsingPOST)
[source,json]
----

{
"headers": [
    {
      "key": "x-amway-seq-number",
      "value": "78090081"
    }
  ],
  "partitions": [
    {
      "id": 0,
      "startPercentage": 60
    },
    {
      "id": 1,
      "startPercentage": 70
    },
    {
      "id": 2,
      "startPercentage": 50
    }
  ],
  "searchStrategy": "PARTITION"
}
----

=== Output Format
This tool returns event payload as base64 encoded strings, base64 decode if the payload is JSON or text