= Kafka Event Finder
:toc: macro

Application that allows you to find an event on a topic

toc::[]

== Configuration

=== Default Port

This aplication doesnt use port 8080 but runs on port 10000 to ensure it doesnt conflict with other applications that are using default spring boot port.
The can be changed, see here[config-link-tbd] for more info

=== Servers

List of servers to connect to. By default, the application doesn't connect to any servers.
Connections can be made using the connect api and connection strings can be managed using the configuration api.
Configurations can be injected without using config API by managing config in `application.yaml` in the `CWD` of the jar file.

===== Server Config Format
----
servers:
  - name: "prod"
    bootstrapServers: firstCluster:9092
    apiKey: default-api-will-not-work
    apiSecret: default-secret-will-not-work
  - name: "preprod"
    bootstrapServers: preprod:8888
    apiKey: default-api-will-not-work
    apiSecret: default-secret-will-not-work
  - name: "perf"
    bootstrapServers: perf:9092
    apiKey: default-api-will-not-work
    apiSecret: default-secret-will-not-work
----

==== Start the application
Provide credentials to Kafka cluster via environment variables
----
export API_KEY=api_key
export API_SECRET=api_secret

----
And run the following gradle command
----
 gradle :app:bootRun

----

=== Get active connections
=== Connect to a server
=== Disconnect from a server


== Find an event
By default all searches begin with the lowest offset the topic has. You can use `partition` search strategy and provide
a `%` of the log to skip over

=== Output Format
This tool assumes you are searching for an event that can be serialized as a string, if you are looking for an event
that isn't serializable as string use following supported content types.

==== Binary Format
You will need to request an `Content-Type: application/base64-encoded` response and decode it yourself
using an appropriate decoded.

==== String Format
Use `Content-Type: text/html; charset=UTF-8`

==== JSON Format
Use `application/json` as the content type
